// Every inline style in the app. There is no CSS file and no class-based
// styling; components read keys off this object. Grouped shared-first, then
// by the page that owns them (timer, landing page, gym tracker).
const styles = {
  screen: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    fontFamily:
      "'Helvetica Neue', 'Arial Narrow', -apple-system, BlinkMacSystemFont, sans-serif",
    color: "#fff",
    userSelect: "none",
  },
  setupWrap: {
    maxWidth: 440,
    width: "100%",
    margin: "0 auto",
    padding: "36px 20px 48px",
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
  },
  eyebrow: {
    fontSize: 13,
    letterSpacing: "0.3em",
    color: "#5B8DEF",
    fontWeight: 700,
    marginBottom: 10,
  },
  setupTitle: {
    fontSize: 38,
    lineHeight: 1.05,
    fontWeight: 800,
    letterSpacing: "-0.02em",
    margin: 0,
  },
  backLink: {
    padding: "8px 14px",
    borderRadius: 10,
    border: "1.5px solid #26324A",
    background: "#141C2C",
    color: "#5B8DEF",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  editedTag: { fontSize: 16, fontWeight: 600, color: "#5B8DEF", verticalAlign: "middle" },
  previewMeta: { fontSize: 15, color: "#8FA3BF", fontWeight: 500, marginTop: 6 },
  previewHint: { fontSize: 13, color: "#5B8DEF", fontWeight: 600, marginTop: 6 },
  infoIcon: { fontSize: 13, color: "#5B8DEF", marginLeft: 8, fontWeight: 400 },
  descBox: {
    padding: "10px 14px 14px 38px",
    fontSize: 14,
    color: "#B9C6DB",
    lineHeight: 1.5,
    borderBottom: "1px solid #26324A",
    background: "#121A29",
  },
  presetCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "18px 18px",
    borderRadius: 16,
    border: "2px solid #26324A",
    background: "#141C2C",
    cursor: "pointer",
  },
  presetCardName: {
    fontSize: 19,
    fontWeight: 800,
    marginBottom: 4,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  // A card can carry both badges at once, so neither may absorb the squeeze
  // when a long preset name shares the row with them.
  customBadge: {
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: "0.1em",
    color: "#6EE7B7",
    border: "1px solid #6EE7B7",
    borderRadius: 6,
    padding: "2px 6px",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  repsBadge: {
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: "0.1em",
    color: "#FDE68A",
    border: "1px solid #FDE68A",
    borderRadius: 6,
    padding: "2px 6px",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  presetCardMeta: { fontSize: 13, color: "#8FA3BF", fontWeight: 500 },
  presetArrow: { fontSize: 28, color: "#5B8DEF", fontWeight: 400 },
  pageHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    minHeight: 40,
    marginBottom: 20,
  },
  accountMenuWrap: { position: "relative", flexShrink: 0, zIndex: 20 },
  accountBtn: {
    padding: "8px 14px",
    borderRadius: 999,
    border: "1.5px solid #26324A",
    background: "#141C2C",
    color: "#8FA3BF",
    fontSize: 13,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  accountChip: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "5px 10px 5px 6px",
    borderRadius: 999,
    border: "1.5px solid #26324A",
    background: "#141C2C",
    fontFamily: "inherit",
    cursor: "pointer",
  },
  accountCaret: { fontSize: 10, color: "#5F7290" },
  avatarFallback: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    fontSize: 15,
    fontWeight: 800,
    color: "#B9C6DB",
    background: "#26324A",
  },
  menuBackdrop: { position: "fixed", inset: 0, zIndex: 1, background: "transparent" },
  accountMenu: {
    position: "absolute",
    top: 44,
    right: 0,
    zIndex: 2,
    minWidth: 220,
    maxWidth: "calc(100vw - 40px)",
    background: "#141C2C",
    border: "1.5px solid #26324A",
    borderRadius: 14,
    padding: 14,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    boxShadow: "0 12px 32px rgba(0, 0, 0, 0.45)",
  },
  accountMenuHeader: { display: "flex", alignItems: "center", gap: 10, minWidth: 0 },
  accountPhoto: { width: 28, height: 28, borderRadius: "50%", flexShrink: 0 },
  accountName: {
    fontSize: 14,
    fontWeight: 700,
    color: "#B9C6DB",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  syncHint: { fontSize: 12, fontWeight: 600, whiteSpace: "nowrap" },
  signInHint: { marginTop: 18, fontSize: 13, fontWeight: 600, color: "#5F7290" },
  signOutLink: {
    background: "none",
    border: "none",
    borderTop: "1px solid #26324A",
    color: "#5B8DEF",
    fontSize: 13,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
    textAlign: "left",
    padding: "10px 0 2px",
    marginTop: 2,
  },
  // ---- Sign-in dialog (shares confirmOverlay as its backdrop) ----
  authBox: {
    width: "100%",
    maxWidth: 340,
    maxHeight: "calc(100vh - 48px)",
    overflowY: "auto",
    background: "#141C2C",
    border: "1.5px solid #26324A",
    borderRadius: 16,
    padding: 20,
    boxSizing: "border-box",
  },
  authSubtitle: {
    fontSize: 13,
    color: "#8FA3BF",
    fontWeight: 500,
    lineHeight: 1.4,
    marginBottom: 16,
  },
  authGoogleBtn: {
    width: "100%",
    padding: "12px 0",
    borderRadius: 12,
    border: "1.5px solid #3B4A63",
    background: "#1B2436",
    color: "#E6EDF7",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  authDivider: { display: "flex", alignItems: "center", gap: 10, margin: "16px 0" },
  authDividerLine: { flex: 1, height: 1, background: "#26324A" },
  authDividerText: { fontSize: 12, fontWeight: 700, color: "#5F7290" },
  authLabel: {
    display: "block",
    fontSize: 12,
    fontWeight: 700,
    color: "#8FA3BF",
    marginBottom: 6,
  },
  authInput: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: 12,
    border: "2px solid #3B4A63",
    background: "#161F30",
    color: "#fff",
    fontSize: 16, // 16px keeps iOS Safari from zooming the page on focus
    fontFamily: "inherit",
    outline: "none",
    boxSizing: "border-box",
  },
  authForgotRow: { display: "flex", justifyContent: "flex-end", marginTop: 2 },
  authForgot: {
    display: "flex",
    alignItems: "center",
    minHeight: 44, // a thumb's worth: a near miss below this hits the password field
    padding: "0 6px",
    background: "none",
    border: "none",
    color: "#8FA3BF",
    fontSize: 12,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  authNotice: {
    marginTop: 12,
    fontSize: 13,
    fontWeight: 600,
    color: "#7FD1A7",
    lineHeight: 1.4,
  },
  authError: {
    marginTop: 12,
    fontSize: 13,
    fontWeight: 600,
    color: "#FCA5A5",
    lineHeight: 1.4,
  },
  authSubmit: {
    width: "100%",
    marginTop: 16,
    padding: "13px 0",
    borderRadius: 12,
    border: "none",
    background: "#5B8DEF",
    color: "#fff",
    fontSize: 15,
    fontWeight: 800,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  authSwitch: {
    width: "100%",
    marginTop: 14,
    background: "none",
    border: "none",
    color: "#5B8DEF",
    fontSize: 13,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
    padding: 0,
  },
  authCancel: {
    width: "100%",
    marginTop: 12,
    background: "none",
    border: "none",
    color: "#5F7290",
    fontSize: 13,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
    padding: 0,
  },
  confirmOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    background: "rgba(8, 12, 20, 0.7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  confirmBox: {
    width: "100%",
    maxWidth: 320,
    background: "#141C2C",
    border: "1.5px solid #26324A",
    borderRadius: 16,
    padding: 20,
    boxSizing: "border-box",
  },
  confirmTitle: { fontSize: 17, fontWeight: 800, marginBottom: 8 },
  confirmText: { fontSize: 14, color: "#8FA3BF", fontWeight: 500, marginBottom: 18, lineHeight: 1.4 },
  confirmActions: { display: "flex", gap: 10 },
  confirmCancel: {
    flex: 1,
    padding: "11px 0",
    borderRadius: 12,
    border: "1.5px solid #26324A",
    background: "transparent",
    color: "#B9C6DB",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  confirmDeleteBtn: {
    flex: 1,
    padding: "11px 0",
    borderRadius: 12,
    border: "none",
    background: "#E5484D",
    color: "#fff",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  cardDelete: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    border: "none",
    background: "#3B4A63",
    color: "#fff",
    fontSize: 16,
    cursor: "pointer",
    padding: 0,
    flexShrink: 0,
  },
  previewRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "13px 0",
    borderBottom: "1px solid #26324A",
  },
  previewIndex: {
    width: 24,
    fontSize: 13,
    fontWeight: 800,
    color: "#5B8DEF",
    fontVariantNumeric: "tabular-nums",
  },
  previewTiming: { display: "flex", gap: 12, marginTop: 24 },
  timingItem: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "14px 12px",
    borderRadius: 14,
    background: "#141C2C",
    border: "1px solid #26324A",
    textAlign: "center",
  },
  timingValue: { fontSize: 22, fontWeight: 800, fontVariantNumeric: "tabular-nums" },
  timingLabel: { fontSize: 11, color: "#8FA3BF", fontWeight: 600, lineHeight: 1.3 },
  notifyRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    marginTop: 24,
    padding: "14px 16px",
    borderRadius: 14,
    border: "1px solid #26324A",
    background: "#141C2C",
    textAlign: "left",
    font: "inherit",
  },
  notifyIcon: { fontSize: 20, lineHeight: 1 },
  notifyLabel: { display: "block", fontSize: 14.5, fontWeight: 700, color: "#E6EDF9" },
  notifyHint: { display: "block", fontSize: 12, color: "#8FA3BF", marginTop: 4, lineHeight: 1.4 },
  switchTrack: {
    flexShrink: 0,
    width: 44,
    height: 26,
    borderRadius: 13,
    padding: 3,
    display: "flex",
    alignItems: "center",
    transition: "background 0.18s ease",
  },
  switchKnob: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    background: "#fff",
    transition: "transform 0.18s ease",
  },
  sectionLabel: {
    fontSize: 12,
    letterSpacing: "0.2em",
    color: "#8FA3BF",
    fontWeight: 700,
    margin: "24px 0 10px",
  },
  // ---- Timed / reps mode picker (edit screen) ----
  modeToggle: { display: "flex", gap: 10 },
  modeBtn: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 3,
    padding: "12px 10px",
    borderRadius: 12,
    border: "2px solid #3B4A63",
    fontFamily: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  modeBtnLabel: { fontSize: 15, fontWeight: 800 },
  modeBtnHint: { fontSize: 11.5, fontWeight: 600, color: "#8FA3BF", lineHeight: 1.3 },
  exList: { borderTop: "1px solid #26324A" },
  exRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "0 4px",
  },
  dragHandle: {
    fontSize: 20,
    color: "#5B8DEF",
    cursor: "grab",
    padding: "10px 12px 10px 4px",
    touchAction: "none",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  exName: { fontSize: 16, fontWeight: 600, flex: 1 },
  exDur: {
    fontSize: 14,
    fontWeight: 700,
    color: "#5B8DEF",
    fontVariantNumeric: "tabular-nums",
  },
  removeBtn: {
    background: "none",
    border: "none",
    color: "#8FA3BF",
    fontSize: 22,
    cursor: "pointer",
    padding: "0 4px",
    lineHeight: 1,
  },
  durBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    border: "1px solid #3B4A63",
    background: "transparent",
    color: "#fff",
    fontSize: 15,
    fontWeight: 800,
    cursor: "pointer",
    padding: 0,
    lineHeight: 1,
    flexShrink: 0,
  },
  libInfo: {
    padding: "8px 12px 8px 8px",
    border: "none",
    background: "transparent",
    fontSize: 15,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  addToggle: {
    marginTop: 14,
    padding: "12px",
    borderRadius: 12,
    border: "2px dashed #3B4A63",
    background: "transparent",
    color: "#8FA3BF",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
  },
  libDescBox: {
    padding: "10px 14px 14px",
    fontSize: 14,
    color: "#B9C6DB",
    lineHeight: 1.5,
    background: "#121A29",
    borderBottom: "1px solid #26324A",
  },
  stepperRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 0",
    borderBottom: "1px solid #26324A",
  },
  stepperLabel: { fontSize: 15, fontWeight: 600, color: "#D7E0EF" },
  stepperCtrl: { display: "flex", alignItems: "center", gap: 4 },
  stepBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    border: "2px solid #3B4A63",
    background: "transparent",
    color: "#fff",
    fontSize: 20,
    fontWeight: 800,
    cursor: "pointer",
  },
  stepValue: {
    minWidth: 58,
    textAlign: "center",
    fontSize: 17,
    fontWeight: 800,
    fontVariantNumeric: "tabular-nums",
  },
  updateBtn: {
    width: "100%",
    padding: "14px",
    borderRadius: 12,
    border: "none",
    background: "#047857",
    color: "#fff",
    fontSize: 15,
    fontWeight: 800,
    cursor: "pointer",
    boxSizing: "border-box",
  },
  saveRow: { display: "flex", gap: 10 },
  saveInput: {
    flex: 1,
    padding: "12px 14px",
    borderRadius: 12,
    border: "2px solid #3B4A63",
    background: "#161F30",
    color: "#fff",
    fontSize: 15,
    outline: "none",
    minWidth: 0,
  },
  saveBtn: {
    padding: "12px 20px",
    borderRadius: 12,
    border: "none",
    background: "#3B4A63",
    color: "#fff",
    fontSize: 15,
    fontWeight: 800,
    cursor: "pointer",
  },
  saveMsg: { marginTop: 8, fontSize: 14, color: "#6EE7B7", fontWeight: 600 },
  startBtn: {
    marginTop: 28,
    padding: "20px",
    borderRadius: 16,
    border: "none",
    background: "#1D4ED8",
    color: "#fff",
    fontSize: 17,
    fontWeight: 800,
    letterSpacing: "0.1em",
    cursor: "pointer",
  },
  editBtn: {
    marginTop: 12,
    padding: "16px",
    borderRadius: 16,
    border: "2px solid #3B4A63",
    background: "transparent",
    color: "#B9C6DB",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
  },
  doneWrap: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    padding: 24,
  },
  doneTitle: { fontSize: 40, fontWeight: 800, margin: "16px 0 8px" },
  doneSub: { fontSize: 16, color: "#9CA3AF", margin: 0 },
  topBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "20px 24px",
  },
  phaseTag: { fontSize: 14, fontWeight: 800, letterSpacing: "0.25em" },
  roundTag: { fontSize: 14, fontWeight: 700, letterSpacing: "0.15em" },
  iconBtn: { background: "none", border: "none", fontSize: 20, cursor: "pointer", padding: 4 },
  centerBlock: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 24px",
    textAlign: "center",
  },
  exerciseName: {
    fontSize: "clamp(28px, 7vw, 44px)",
    fontWeight: 800,
    letterSpacing: "-0.01em",
    marginBottom: 8,
  },
  cue: { fontSize: 15, fontWeight: 500, maxWidth: 340, lineHeight: 1.4 },
  bigTime: {
    fontSize: "clamp(96px, 28vw, 180px)",
    fontWeight: 900,
    lineHeight: 1,
    fontVariantNumeric: "tabular-nums",
    letterSpacing: "-0.03em",
    margin: "16px 0 24px",
  },
  // ---- Open rep set (the tap-to-continue screen) ----
  repsUnit: { fontSize: 15, fontWeight: 800, letterSpacing: "0.2em", marginTop: -12 },
  tapPrompt: {
    marginTop: 20,
    padding: "12px 22px",
    borderRadius: 999,
    border: "2px dashed rgba(255,255,255,0.45)",
    fontSize: 13,
    fontWeight: 800,
    letterSpacing: "0.15em",
    color: "rgba(255,255,255,0.9)",
  },
  progressTrack: {
    width: "100%",
    maxWidth: 360,
    height: 8,
    borderRadius: 4,
    background: "rgba(255,255,255,0.2)",
    overflow: "hidden",
  },
  progressFill: { height: "100%", borderRadius: 4, transition: "width 1s linear" },
  dots: { display: "flex", gap: 10, marginTop: 24, flexWrap: "wrap", justifyContent: "center" },
  dot: { width: 12, height: 12, borderRadius: "50%" },
  upNext: { marginTop: 24, fontSize: 13, fontWeight: 700, letterSpacing: "0.15em" },
  controls: {
    display: "flex",
    gap: 12,
    padding: "0 24px 32px",
    maxWidth: 480,
    width: "100%",
    margin: "0 auto",
    boxSizing: "border-box",
  },
  ctrlBtnPrimary: {
    flex: 2,
    padding: "18px",
    borderRadius: 14,
    border: "none",
    background: "rgba(255,255,255,0.95)",
    color: "#111",
    fontSize: 17,
    fontWeight: 800,
    cursor: "pointer",
  },
  ctrlBtnSecondary: {
    flex: 1,
    padding: "18px",
    borderRadius: 14,
    border: "2px solid rgba(255,255,255,0.4)",
    background: "transparent",
    color: "#fff",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
  },
  // ---- Exercise picker (both catalogs: timer library and gym log) ----
  emptyText: { padding: "14px 0", color: "#8FA3BF", fontSize: 14, lineHeight: 1.5 },
  searchInput: {
    width: "100%",
    padding: "13px 14px",
    borderRadius: 12,
    border: "2px solid #3B4A63",
    background: "#161F30",
    color: "#fff",
    fontSize: 16,
    outline: "none",
    boxSizing: "border-box",
  },
  groupChips: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 12 },
  groupChip: {
    padding: "7px 12px",
    borderRadius: 999,
    border: "1px solid #3B4A63",
    background: "#161F30",
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  resultRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 4px",
    borderBottom: "1px solid #26324A",
    cursor: "pointer",
  },
  resultName: { fontSize: 15, fontWeight: 700 },
  // One line, clipped — the row has to stay scannable next to the duration,
  // and the full cue and description are one ⓘ tap away.
  resultMeta: {
    fontSize: 13,
    color: "#8FA3BF",
    fontWeight: 500,
    marginTop: 2,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  resultDur: { fontSize: 13, fontWeight: 700, color: "#5B8DEF", fontVariantNumeric: "tabular-nums" },

  // ---- Loading skeletons ----
  skeletonCard: {
    display: "flex",
    alignItems: "center",
    padding: "19px 18px",
    borderRadius: 16,
    border: "2px solid #1D2739",
    background: "#121927",
  },
  // ---- Landing page / header nav ----
  homeBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 38,
    height: 38,
    borderRadius: 10,
    border: "1.5px solid #26324A",
    background: "#141C2C",
    color: "#5B8DEF",
    cursor: "pointer",
    padding: 0,
    flexShrink: 0,
  },
  homeNavCard: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "22px 18px",
    borderRadius: 16,
    border: "2px solid #26324A",
    background: "#141C2C",
    cursor: "pointer",
  },
  homeNavEmoji: { fontSize: 30 },
  // ---- Gym tracker ----
  gymActiveHint: { marginTop: 10, fontSize: 13, fontWeight: 600, color: "#6EE7B7" },
  gymFinishHint: {
    marginTop: 10,
    fontSize: 12.5,
    color: "#8FA3BF",
    lineHeight: 1.4,
    textAlign: "center",
  },
  gymLastBadge: {
    fontSize: 12,
    fontWeight: 700,
    color: "#6EE7B7",
    border: "1px solid #2E4A3F",
    borderRadius: 8,
    padding: "3px 8px",
    whiteSpace: "nowrap",
    fontVariantNumeric: "tabular-nums",
    flexShrink: 0,
  },
  gymEntryCard: {
    borderRadius: 14,
    border: "1px solid #26324A",
    background: "#141C2C",
    padding: "14px 14px 12px",
    marginBottom: 12,
  },
  gymEntryHead: { display: "flex", alignItems: "flex-start", gap: 8, marginBottom: 8 },
  gymEntryName: { fontSize: 16, fontWeight: 800 },
  gymEntryHe: { fontSize: 13, color: "#8FA3BF", fontWeight: 500, marginTop: 2 },
  gymLastHint: { color: "#6EE7B7", fontVariantNumeric: "tabular-nums" },
  gymSetRow: { display: "flex", alignItems: "center", gap: 8, padding: "5px 0" },
  gymSetIndex: {
    width: 20,
    fontSize: 13,
    fontWeight: 800,
    color: "#5B8DEF",
    fontVariantNumeric: "tabular-nums",
  },
  gymSetInput: {
    width: 64,
    padding: "9px 8px",
    borderRadius: 10,
    border: "1.5px solid #3B4A63",
    background: "#161F30",
    color: "#fff",
    fontSize: 15,
    fontWeight: 700,
    textAlign: "center",
    outline: "none",
    fontVariantNumeric: "tabular-nums",
    boxSizing: "border-box",
  },
  gymSetSep: { fontSize: 13, color: "#8FA3BF", fontWeight: 600 },
  gymAddSetBtn: {
    marginTop: 8,
    padding: "8px 14px",
    borderRadius: 10,
    border: "1.5px dashed #3B4A63",
    background: "transparent",
    color: "#8FA3BF",
    fontSize: 13,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  gymHistoryCard: {
    borderRadius: 16,
    border: "2px solid #26324A",
    background: "#141C2C",
    padding: "16px 18px",
  },
  gymHistoryHead: { display: "flex", alignItems: "center", gap: 12, cursor: "pointer" },
  gymHistoryDate: { fontSize: 16, fontWeight: 800, marginBottom: 4 },
  gymHistoryEx: { marginTop: 12, paddingTop: 10, borderTop: "1px solid #26324A" },
  gymHistoryExName: { fontSize: 14, fontWeight: 700 },
  gymHistorySets: {
    marginTop: 4,
    fontSize: 13,
    color: "#B9C6DB",
    fontWeight: 600,
    fontVariantNumeric: "tabular-nums",
    lineHeight: 1.6,
  },
};
